export type TierRequirement = 'api_access' | 'raw_data';

export type ToolPolicy = {
  requires: TierRequirement;
  mutation: boolean;
  degradesWith?: readonly string[];
};

export const TIER_POLICY = {
  list_projects: { requires: 'api_access', mutation: false },
  search_projects: { requires: 'api_access', mutation: false },
  list_contacts: { requires: 'api_access', mutation: false },
  search_contacts: { requires: 'api_access', mutation: false },
  get_contact: { requires: 'api_access', mutation: false },
  create_contact: { requires: 'api_access', mutation: true },
  update_contact: { requires: 'api_access', mutation: true },
  delete_contact: { requires: 'api_access', mutation: true },
  get_event: { requires: 'api_access', mutation: false },
  list_event_types: { requires: 'api_access', mutation: false },
  get_org: { requires: 'api_access', mutation: false },
  get_project: { requires: 'api_access', mutation: false, degradesWith: ['design'] },
  get_project_snapshot: { requires: 'api_access', mutation: false },
  create_project: { requires: 'api_access', mutation: true },
  update_project: { requires: 'api_access', mutation: true },
  update_project_stage: { requires: 'api_access', mutation: true },
  update_project_usage: { requires: 'api_access', mutation: true },
  delete_project: { requires: 'api_access', mutation: true },
  list_roles: { requires: 'api_access', mutation: false },
  get_role: { requires: 'api_access', mutation: false },
  list_project_systems: { requires: 'api_access', mutation: false },
  get_system: { requires: 'api_access', mutation: false },
  get_system_details: { requires: 'api_access', mutation: false, degradesWith: ['custom_data'] },
  get_system_image: { requires: 'api_access', mutation: true },
  list_modules: { requires: 'api_access', mutation: false },
  get_module: { requires: 'api_access', mutation: false },
  delete_module_activation: { requires: 'api_access', mutation: true },
  list_inverters: { requires: 'api_access', mutation: false },
  get_inverter: { requires: 'api_access', mutation: false },
  delete_inverter_activation: { requires: 'api_access', mutation: true },
  list_batteries: { requires: 'api_access', mutation: false },
  get_battery: { requires: 'api_access', mutation: false },
  delete_battery_activation: { requires: 'api_access', mutation: true },
  list_other_components: { requires: 'api_access', mutation: false },
  get_other_component: { requires: 'api_access', mutation: false },
  delete_other_component_activation: { requires: 'api_access', mutation: true },
  list_workflows: { requires: 'api_access', mutation: false },
  get_workflow: { requires: 'api_access', mutation: false },
  create_workflow: { requires: 'api_access', mutation: true },
  delete_workflow: { requires: 'api_access', mutation: true },
  list_payment_options: { requires: 'api_access', mutation: false },
  get_payment_option: { requires: 'api_access', mutation: false },
  delete_payment_option: { requires: 'api_access', mutation: true },
  list_pricing_schemes: { requires: 'api_access', mutation: false },
  get_pricing_scheme: { requires: 'api_access', mutation: false },
  delete_pricing_scheme: { requires: 'api_access', mutation: true },
  list_costings: { requires: 'api_access', mutation: false },
  get_costing: { requires: 'api_access', mutation: false },
  delete_costing: { requires: 'api_access', mutation: true },
  list_roof_types: { requires: 'api_access', mutation: false },
  list_file_tags: { requires: 'api_access', mutation: false },
  list_private_files: { requires: 'api_access', mutation: false },
  get_private_file: { requires: 'api_access', mutation: false },
  create_private_file: { requires: 'api_access', mutation: true },
  update_private_file: { requires: 'api_access', mutation: true },
  delete_private_file: { requires: 'api_access', mutation: true },
  generate_project_document: { requires: 'api_access', mutation: true },
  list_webhooks: { requires: 'api_access', mutation: false },
  create_webhook: { requires: 'api_access', mutation: true },
  update_webhook: { requires: 'api_access', mutation: true },
  list_webhook_logs: { requires: 'api_access', mutation: false },
  list_webhook_queue: { requires: 'api_access', mutation: false },
  list_connected_orgs: { requires: 'api_access', mutation: false },
  list_connection_requests: { requires: 'api_access', mutation: false },
  create_connection_request: { requires: 'api_access', mutation: true },
  accept_connection_request: { requires: 'api_access', mutation: true },
  update_connection: { requires: 'api_access', mutation: true },
  delete_connection: { requires: 'api_access', mutation: true },
  share_project: { requires: 'api_access', mutation: true },
  share_entities: { requires: 'api_access', mutation: true },
  create_permission_role: { requires: 'api_access', mutation: true },
  get_proposal_data: { requires: 'raw_data', mutation: false },
  get_project_design: { requires: 'raw_data', mutation: false },
} as const satisfies Record<string, ToolPolicy>;

export type ToolName = keyof typeof TIER_POLICY;
