/** Document types from the Generating Project Files page. */
export const DOCUMENT_TYPES = [
  'proposal',
  'proposal_only',
  'contract',
  'contract_only',
  'owners_manual',
  'installation_instructions',
  'energy_yield_report',
  'shade_report',
  'structural_report_mcs',
  'pv_site_plan',
  'system_image_only',
  'system_performance_image_only',
  'ironridge_bom',
  'global_bom',
  'change_order',
  'generic_document',
  'financials_report',
  'greenlancer_project_summary',
  'lightreach_sales_design_details',
  'system_performance_8760',
  'bill_calculations_csv',
] as const;
